// <auto-generated />
using System;
using MatchEdge.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MatchEdge.Infrastructure.Migrations
{
    [DbContext(typeof(MatchEdgeDbContext))]
    [Migration("20260905205450_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.30");

            modelBuilder.Entity("MatchEdge.Infrastructure.Data.Entities.HistoricalOddsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AwayTeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("AwayWinOdds")
                        .HasPrecision(10, 4)
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("DrawOdds")
                        .HasPrecision(10, 4)
                        .HasColumnType("REAL");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HomeTeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("HomeWinOdds")
                        .HasPrecision(10, 4)
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("MappedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SofaScoreAwayTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SofaScoreEventId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SofaScoreHomeTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceMatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SofaScoreEventId");

                    b.HasIndex("Source", "SourceMatchId")
                        .IsUnique();

                    b.HasIndex("MatchDate", "HomeTeamId", "AwayTeamId");

                    b.ToTable("HistoricalOdds");
                });

            modelBuilder.Entity("MatchEdge.Infrastructure.Data.Entities.MatchMappingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("MatchConfidence")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SofaScoreEventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceMatchId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SofaScoreEventId");

                    b.HasIndex("Source", "SourceMatchId")
                        .IsUnique();

                    b.ToTable("MatchMappings");
                });

            modelBuilder.Entity("MatchEdge.Infrastructure.Data.Entities.TeamMappingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SofaScoreTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SofaScoreTeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceTeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SofaScoreTeamId");

                    b.HasIndex("Source", "SourceTeamId")
                        .IsUnique();

                    b.ToTable("TeamMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
