// <auto-generated />
using System;
using MatchEdge.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MatchEdge.Infrastructure.Migrations
{
    [DbContext(typeof(MatchEdgeDbContext))]
    partial class MatchEdgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.31");

            modelBuilder.Entity("MatchEdge.Infrastructure.Data.Entities.DailyPickEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Edge")
                        .HasPrecision(10, 4)
                        .HasColumnType("REAL");

                    b.Property<double>("HitRate")
                        .HasColumnType("REAL");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Odds")
                        .HasPrecision(10, 4)
                        .HasColumnType("REAL");

                    b.Property<int?>("PickOutcomeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SampleSize")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Score")
                        .HasPrecision(10, 4)
                        .HasColumnType("REAL");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("StakeUnits")
                        .HasPrecision(10, 4)
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TrendResultId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("Status");

                    b.HasIndex("TrendResultId");

                    b.HasIndex("Date", "Team", "Market")
                        .IsUnique();

                    b.ToTable("DailyPicks");
                });

            modelBuilder.Entity("MatchEdge.Infrastructure.Data.Entities.HistoricalOddsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AwayTeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("AwayWinOdds")
                        .HasPrecision(10, 4)
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("DrawOdds")
                        .HasPrecision(10, 4)
                        .HasColumnType("REAL");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HomeTeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("HomeWinOdds")
                        .HasPrecision(10, 4)
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("MappedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SofaScoreAwayTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SofaScoreEventId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SofaScoreHomeTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceMatchId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SofaScoreEventId");

                    b.HasIndex("Source", "SourceMatchId")
                        .IsUnique();

                    b.HasIndex("MatchDate", "HomeTeamId", "AwayTeamId");

                    b.ToTable("HistoricalOdds");
                });

            modelBuilder.Entity("MatchEdge.Infrastructure.Data.Entities.MatchMappingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("MatchConfidence")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SofaScoreEventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceMatchId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SofaScoreEventId");

                    b.HasIndex("Source", "SourceMatchId")
                        .IsUnique();

                    b.ToTable("MatchMappings");
                });

            modelBuilder.Entity("MatchEdge.Infrastructure.Data.Entities.PickOutcomeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BalanceAfter")
                        .HasPrecision(10, 4)
                        .HasColumnType("REAL");

                    b.Property<int>("DailyPickId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("Odds")
                        .HasPrecision(10, 4)
                        .HasColumnType("REAL");

                    b.Property<double>("Profit")
                        .HasPrecision(10, 4)
                        .HasColumnType("REAL");

                    b.Property<double>("ProfitUnits")
                        .HasPrecision(10, 4)
                        .HasColumnType("REAL");

                    b.Property<string>("ResultDetail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Won")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DailyPickId");

                    b.HasIndex("MatchDate");

                    b.HasIndex("Won");

                    b.ToTable("PickOutcomes");
                });

            modelBuilder.Entity("MatchEdge.Infrastructure.Data.Entities.TeamMappingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SofaScoreTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SofaScoreTeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceTeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceTeamName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SofaScoreTeamId");

                    b.HasIndex("Source", "SourceTeamId")
                        .IsUnique();

                    b.ToTable("TeamMappings");
                });

            modelBuilder.Entity("MatchEdge.Infrastructure.Data.Entities.TrendResultEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AvgValue")
                        .HasColumnType("REAL");

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DailyPickId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Edge")
                        .HasPrecision(10, 4)
                        .HasColumnType("REAL");

                    b.Property<string>("Fixture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FixtureApid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FixtureSlug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HitCount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HitDenominator")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HitNumerator")
                        .HasColumnType("INTEGER");

                    b.Property<double>("HitRate")
                        .HasColumnType("REAL");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<string>("League")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Market")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Odds")
                        .HasPrecision(10, 4)
                        .HasColumnType("REAL");

                    b.Property<int>("OppHitRate")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RatePercentage")
                        .HasColumnType("REAL");

                    b.Property<double>("Score")
                        .HasPrecision(10, 4)
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ScrapedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamSlug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Classification");

                    b.HasIndex("FixtureApid");

                    b.HasIndex("IsSelected");

                    b.HasIndex("ScrapedAt");

                    b.HasIndex("FixtureApid", "Team", "Market");

                    b.ToTable("TrendResults");
                });
#pragma warning restore 612, 618
        }
    }
}
