namespace MatchEdge.Domain.Models;

public class TeamStatistics
{
    public int GoalsScored { get; set; }
    public int GoalsConceded { get; set; }
    public int OwnGoals { get; set; }
    public int Assists { get; set; }
    public int PenaltyGoals { get; set; }
    public int PenaltiesTaken { get; set; }
    public int FreeKickGoals { get; set; }
    public int FreeKickShots { get; set; }
    public int GoalsFromInsideTheBox { get; set; }
    public int GoalsFromOutsideTheBox { get; set; }
    public int HeadedGoals { get; set; }
    public int LeftFootGoals { get; set; }
    public int RightFootGoals { get; set; }
    public int Shots { get; set; }
    public int ShotsFromInsideTheBox { get; set; }
    public int ShotsFromOutsideTheBox { get; set; }
    public int ShotsOnTarget { get; set; }
    public int ShotsOffTarget { get; set; }
    public int BlockedScoringAttempt { get; set; }
    public int HitWoodwork { get; set; }
    public int BigChances { get; set; }
    public int BigChancesCreated { get; set; }
    public int BigChancesMissed { get; set; }
    public int SuccessfulDribbles { get; set; }
    public int DribbleAttempts { get; set; }
    public int Corners { get; set; }
    public int FastBreaks { get; set; }
    public int FastBreakGoals { get; set; }
    public int FastBreakShots { get; set; }
    public double AverageBallPossession { get; set; }
    public int TotalPasses { get; set; }
    public int AccuratePasses { get; set; }
    public double AccuratePassesPercentage { get; set; }
    public int TotalOwnHalfPasses { get; set; }
    public int AccurateOwnHalfPasses { get; set; }
    public double AccurateOwnHalfPassesPercentage { get; set; }
    public int TotalOppositionHalfPasses { get; set; }
    public int AccurateOppositionHalfPasses { get; set; }
    public double AccurateOppositionHalfPassesPercentage { get; set; }
    public int TotalLongBalls { get; set; }
    public int AccurateLongBalls { get; set; }
    public double AccurateLongBallsPercentage { get; set; }
    public int TotalCrosses { get; set; }
    public int AccurateCrosses { get; set; }
    public double AccurateCrossesPercentage { get; set; }
    public int CleanSheets { get; set; }
    public int Tackles { get; set; }
    public int Interceptions { get; set; }
    public int Saves { get; set; }
    public int ErrorsLeadingToGoal { get; set; }
    public int ErrorsLeadingToShot { get; set; }
    public int PenaltiesCommited { get; set; }
    public int PenaltyGoalsConceded { get; set; }
    public int Clearances { get; set; }
    public int ClearancesOffLine { get; set; }
    public int LastManTackles { get; set; }
    public int TotalDuels { get; set; }
    public int DuelsWon { get; set; }
    public double DuelsWonPercentage { get; set; }
    public int TotalGroundDuels { get; set; }
    public int GroundDuelsWon { get; set; }
    public double GroundDuelsWonPercentage { get; set; }
    public int TotalAerialDuels { get; set; }
    public int AerialDuelsWon { get; set; }
    public double AerialDuelsWonPercentage { get; set; }
    public int PossessionLost { get; set; }
    public int Offsides { get; set; }
    public int Fouls { get; set; }
    public int YellowCards { get; set; }
    public int YellowRedCards { get; set; }
    public int RedCards { get; set; }
    public double AvgRating { get; set; }
    public int AccurateFinalThirdPassesAgainst { get; set; }
    public int AccurateOppositionHalfPassesAgainst { get; set; }
    public int AccurateOwnHalfPassesAgainst { get; set; }
    public int AccuratePassesAgainst { get; set; }
    public int BigChancesAgainst { get; set; }
    public int BigChancesCreatedAgainst { get; set; }
    public int BigChancesMissedAgainst { get; set; }
    public int ClearancesAgainst { get; set; }
    public int CornersAgainst { get; set; }
    public int CrossesSuccessfulAgainst { get; set; }
    public int CrossesTotalAgainst { get; set; }
    public int DribbleAttemptsTotalAgainst { get; set; }
    public int DribbleAttemptsWonAgainst { get; set; }
    public int ErrorsLeadingToGoalAgainst { get; set; }
    public int ErrorsLeadingToShotAgainst { get; set; }
    public int HitWoodworkAgainst { get; set; }
    public int InterceptionsAgainst { get; set; }
    public int KeyPassesAgainst { get; set; }
    public int LongBallsSuccessfulAgainst { get; set; }
    public int LongBallsTotalAgainst { get; set; }
    public int OffsidesAgainst { get; set; }
    public int RedCardsAgainst { get; set; }
    public int ShotsAgainst { get; set; }
    public int ShotsBlockedAgainst { get; set; }
    public int ShotsFromInsideTheBoxAgainst { get; set; }
    public int ShotsFromOutsideTheBoxAgainst { get; set; }
    public int ShotsOffTargetAgainst { get; set; }
    public int ShotsOnTargetAgainst { get; set; }
    public int BlockedScoringAttemptAgainst { get; set; }
    public int TacklesAgainst { get; set; }
    public int TotalFinalThirdPassesAgainst { get; set; }
    public int OppositionHalfPassesTotalAgainst { get; set; }
    public int OwnHalfPassesTotalAgainst { get; set; }
    public int TotalPassesAgainst { get; set; }
    public int YellowCardsAgainst { get; set; }
    public int ThrowIns { get; set; }
    public int GoalKicks { get; set; }
    public int BallRecovery { get; set; }
    public int FreeKicks { get; set; }
    public double KilometersCovered { get; set; }
    public int NumberOfSprints { get; set; }
    public int Id { get; set; }
    public int Matches { get; set; }
    public int AwardedMatches { get; set; }
    public StatisticsType StatisticsType { get; set; } = new();
}
